config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  resources :orders, except: :edit do
    member do
      post :new_member
    end
    resources :items, only: [:create, :destroy]
  end
  resources :groups do
    member do
      post :new_member
      delete :delete_member
    end
 end
 
  devise_for :users , :controllers => { :omniauth_callbacks => "callbacks" }

  sockets_for :notifications , only: [:show]
  
  sockets_for :users do
    sockets_for :notifications
  end

  get 'theorders/my_orders(.:format)', to: 'home#getorderbyuser'
  get 'theorders/friends_orders(.:format)', to: 'home#getorderbyfriends'
  get 'finduser/:id/finduser(.:format)', to: 'home#getuser'
  
  get 'allNotifications/:id', to: 'notifications#html_index'
  get 'notifications/:id/clear' , to: 'notifications#see_all_notification_of_me'
  get 'groups/:id/show_users(.:format)', to: "groups#show_users"
  

 resources :follows
match 'users/newfollow' => 'users#newfollow', :via => :post
 resources :users do
    member do
      get :follow
      get :unfollow
    end
 end

  root  'home#index' 

  
  delete '/orders/:order_id/:user_id', to: 'orders#removeUser', as: 'removeUserfromorder'
  put '/orders/:order_id/:user_id', to: 'orders#joinOrder', as: 'joinuserinorder'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  include Entangled::Model
  entangle
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable ,
         :omniauthable 
       
        acts_as_followable
        acts_as_follower
        has_many :groups
        has_many :orders

        #has_many :orders , :through => :order_user_joins
        #has_many :order_user_joins

        has_many :items
        has_many :notifications, :foreign_key => :user_id

        has_many :user_groups
        has_many :groups, through: :user_groups

        has_many :order_user_joins
        has_many :orders, through: :order_user_joins

        validates_uniqueness_of :name

        
        
  def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.name = auth.info.name
        user.password = Devise.friendly_token[0,20]
      end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  # GET /users
  # GET /users.json
  def index
    @users = User.all
   
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end


  def newfollow
    @email = params[:user][:email]
    puts "***********************" + @email.inspect + "*****************************"
    # Rails.logg

    if @email!=""

    # puts "***********************" + @email + "*****************************"
     @user = User.find_by_email(@email)
     if @user!= nil
      current_user.follow(@user)
      redirect_to users_path
    else
        redirect_to users_path
   end 
   else
     redirect_to users_path {"error "}
    end


  end
  

  def follow
    unless current_user.id == params[:id]
    @user = User.find(params[:id])
    current_user.follow(@user)
    respond_to do |format|
      format.js {render :action=>"follow"}
    end
   end

  end


  def unfollow
    @user = User.find(params[:id])
    current_user.stop_following(@user)
    respond_to do |format|
      format.js {render :action=>"unfollow"}
  end

 end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_user.html.erb
<% unless user == current_user %>
  <% if current_user.following?(user) %>
    <%= link_to(unfollow_user_path(user), :remote => true, :class => 'btn btn-danger') do %>
   <i class="icon-remove icon-white"></i>
   Un-Friend
 <% end %><p></p>
  <% else %>
    <%= link_to(follow_user_path(user) ,:remote => true, :class => 'btn btn-success') do %>
    <i class="icon-ok icon-white"></i>
    Friend
    <%end%><p></p>
  <% end %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :username, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :username, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :nom, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nom, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :prenom, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :prenom, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/_user.html.erb
<% if @users.present? %>
  <%= render @users %>
<% else %>
  <p>There are no user containing the term(s) <%= params[:search] %>.</p>
<% end %>

app/views/users/follow.js.erb
$('#follow_user<%=@user.id%>').html('<%= escape_javascript(render :partial => "users/follow_user", :locals => {:user => @user}) %>');

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="container">
  <div class="page-header">
  <h1>Friends</h1>
</div>
</div>


<div class="container">
<div class="row">
<div class="col-md-4">
  <%= form_for User.new , url: users_newfollow_path do |f| %>
  <p>
  <div class="form-group">
    <h5><%= f.label :email %></h5>
    <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
  </div>
     <%= f.submit "Add Friend", class: 'btn btn-default' %>
</div>
</div>
  
  <!-- class :'btn btn-primary'  -->
</p>
<% end %><br/>

<div class="panel panel-default">
<div class="panel-heading">
  <div class="container">
    <h4>Friends List</h4>
  </div>
</div>
  <div class="panel-body">
  <br>
    <div class="row">
      <% @users.each do |user| %>
        <% unless user == current_user %>
        <% if current_user.following?(user) %>
          <div class="col-md-4">
            <div class="container">
             <img class='img-circle img-responsive'  width='50px' height='40px' src=""/>
              <h4><%= user.name %></h4>
              <span id="follow_user<%=user.id%>">
                <%= link_to(unfollow_user_path(user), :remote => true, :class => 'btn btn-danger') do %>
                  <i class="icon-remove icon-white"></i>
                  Un-Friend
                <% end %><p></p>
            </div>
          </div>
        
        <%end %>
      <% end %>
    <% end %>
</div>
  </div>

</div>
</div>

app/views/users/unfollow.js.erb
$('#follow_user<%=@user.id%>').html('<%= escape_javascript(render :partial => "users/follow_user", :locals => {:user => @user}) %>');