config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  resources :orders, except: :edit do
    member do
      post :new_member
    end
    resources :items, only: [:create, :destroy]
  end
  resources :groups do
    member do
      post :new_member
      delete :delete_member
    end
 end
 
  devise_for :users , :controllers => { :omniauth_callbacks => "callbacks" }

  sockets_for :notifications , only: [:show]
  
  sockets_for :users do
    sockets_for :notifications
  end

  get 'theorders/my_orders(.:format)', to: 'home#getorderbyuser'
  get 'theorders/friends_orders(.:format)', to: 'home#getorderbyfriends'
  get 'finduser/:id/finduser(.:format)', to: 'home#getuser'
  
  get 'allNotifications/:id', to: 'notifications#html_index'
  get 'notifications/:id/clear' , to: 'notifications#see_all_notification_of_me'
  get 'groups/:id/show_users(.:format)', to: "groups#show_users"
  

 resources :follows
match 'users/newfollow' => 'users#newfollow', :via => :post
 resources :users do
    member do
      get :follow
      get :unfollow
    end
 end

  root  'home#index' 

  
  delete '/orders/:order_id/:user_id', to: 'orders#removeUser', as: 'removeUserfromorder'
  put '/orders/:order_id/:user_id', to: 'orders#joinOrder', as: 'joinuserinorder'

end

app/models/order.rb
class Order < ActiveRecord::Base

#	has_and_belongs_to_many :users
	acts_as_followable
	belongs_to :admin, class_name: :User, foreign_key: :user_id
	has_many :order_user_joins
	has_many :users, through: :order_user_joins, dependent: :destroy
	has_many :items, dependent: :destroy

	has_attached_file :image, styles: { medium: "500x500>"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :update, :destroy]
  before_action :authenticate_user!

  arr = Array.new
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.where(user_id: current_user.id.to_i).paginate(:page => params[:page], :per_page => 5)
  end


  # GET /orders/1
  # GET /orders/1.json
  def show
    @order=Order.where(id: params[:id]).take
    if ( (isInvited @order.id, current_user.id) || @order.user_id == current_user.id)
      @order=Order.where(id: params[:id]).take
      @item=Item.new
      @isJoined = (isJoined @order.id, current_user.id)
      @isinvited = (isInvited @order.id, current_user.id)
      @invitedFriends=Array.new
      @joinedFriends=Array.new
      OrderUserJoin.where(:order_id => params[:id]).each do |orderUser|
        @user=User.find(orderUser.user_id)
        @invitedFriends.push(@user)
        if(orderUser.is_joined == 1)
          @joinedFriends.push(@user)
        end
      end
      @orderuserjoin = OrderUserJoin.all
      @users = User.all
    else
      redirect_to orders_path 
    end
  end

  def isInvited order_id, user_id
    OrderUserJoin.where(:order_id => order_id).where(:user_id => user_id).take 
  end

  def isJoined order_id, user_id
    OrderUserJoin.where(:order_id => order_id).where(:user_id => user_id).where(:is_joined => 1).take 
  end


  def new_member
    @email = params[:user][:email]
    @order = Order.find(params[:id])
    if @email !=""
   # puts "***********************" + @email + "*****************************"
     @user = User.find_by_email(@email)
       # puts "***********************" + @group + "*****************************"
      if @user != nil
       if current_user != @user.id
         if current_user.following?(@user)
            puts '************************************ Friend found'
            @userfound = OrderUserJoin.where(:user_id => @user.id , :order_id => @order.id )
            if @userfound.exists? == false 
                @orderuserjoin = OrderUserJoin.new(
                order_id: @order.id,
                user_id: @user.id )
                @orderuserjoin.save
                #  ' Add Frined to Group was successfully created.' 
                 
                redirect_to  order_path(@order.id)
            else 
                  puts '*********************** Frined aready founded .' 
                  redirect_to  order_path(@order.id)
            end 
         else 
           puts '******************* a user not a friend.' 
            redirect_to  order_path(@order.id)
         end
       else 
         puts '******************* trying to add himself to group .' 
          redirect_to  order_path(@order.id)
       end
     else
      puts '******************* not user'
      redirect_to  order_path(@order.id)    
     end
   else
    puts '*******************  email is empty.' 
    redirect_to order_path(@order.id)
 end 
  end
  # GET /orders/new
  def new
    @order = current_user.orders.build


    @friends_id = current_user.follows.map{|u| u.followable_id}

    #@friends_id = User.all.map{ |u| u.id }
    @friends = @friends_id.map{|u| User.find(u)}#current_user.follows.map{|u| User.find(u.followable_id)}
    _group_ids = UserGroup.where(:user_id => current_user.id).map{|ug| ug.group_id}
    @groups = Group.where(user_id: current_user.id);
    #@groups = Group.all
  end

  def create
    if params[:order][:meal] !="" && params[:order][:restaurant] !=""
    @order = Order.new(order_params)
    @order.meal = params[:meal]
    @order.status = "waiting"
    @order.user_id = current_user.id
    @restaurant = @order.restaurant

    puts "loooooooooooooooooooooooooooooooooooooooooooooo"+params[:firendsToBeAdded].to_s
    respond_to do |format|
      if @order.save
        puts params["firendsToBeAdded"]
        @friendsInvited = params[:firendsToBeAdded].split(",").map{|m| m.to_i}.each do |friendId|
          @orderUser=OrderUserJoin.new
          @orderUser.order_id=@order.id
          @orderUser.user_id=friendId
          @orderUser.is_joined=0
          @orderUser.save
          create_notification("#{current_user.name} has invited you to his order",friendId,current_user.id,@order.id)
        end
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  else
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order creation failed.' }
      format.json { head :no_content }
    end
  end
  end




  def joinOrder
    @order=Order.where(id: params[:order_id]).take
    @orderUser=OrderUserJoin.where(:order_id => params[:order_id]).where(:user_id => params[:user_id]).take
    @orderUser.update("is_joined" => 1)
    #create_notification( "<a rel='nofollow' data-method='put' href='/orders/#{params[:order_id]}/#{params[:user_id]}'>Join</a>" , reciever_id = @order.user_id ,sender_id = params[:user_id] )
    create_notification("#{current_user.name} has joined your order",@order.user_id,current_user.id,@order.id)
    redirect_to @order
  end

  def removeUser
    @order=Order.where(id: params[:order_id]).take
    OrderUserJoin.where(:order_id => params[:order_id]).where(:user_id => params[:user_id]).take.destroy
    
    redirect_to @order
  end

  # POST /orders
  # POST /orders.json
  
  
  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    
    respond_to do |format|
      if @order.update("status" => "finished")
        format.html { redirect_to orders_url, notice: 'Order was successfully updated.' }
        format.json { render :index, status: :ok, location: @order }
      else
        format.html { render :index }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:meal, :restaurant, :image )
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <%= form_for @order, html: { multipart: true } do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= label_tag :Order_for %><br>
    <%= text_field_tag :meal %>
  </div>
  <div class="field">
    <%= f.label :From %><br>
    <%= f.text_field :restaurant, :class => "form-control", placeholder: "Enter The restaurant here" %>
  </div>

  <div class="field">
    <%= f.label :Menu %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <input name="firendsToBeAdded" id="firendsToBeAdded" class="hiddenfriends" type="text" value="">
  </div>

  
  <div class="actions">
    <%= f.submit "Add order", class: "btn btn-success" %>
  </div>
<% end %>
    </div>
    

    <div class="col-md-3">
      <div class="panel panel-default">
        <div class="panel-body">
          <div id="friends">
              <h2>added friends</h2>  
          </div>
        </div>
        </div>
    </div>

    <div class="col-md-3">
      <div class="panel panel-default">
        <div class="panel-body">
          <div id="groups">
              <h2>added groups</h2>  
          </div>
        </div>
        </div>
    </div>
    <!--<div class="col-md-6">
    <br/>
      <div class="panel panel-default">
        <div class="panel-body">
        <div class="row">
          
          
<div id="groups">
            <h2>added friends</h2>  
  
</div>
        </div>
          

        </div>
      </div>
    </div>-->
  </div>
</div>


<div class="container">
  <h3>Invite Friend</h3><br/>
  <div class="row">
    <div class="col-md-6">
      <div class="row">
      <% if @friends and @friends.length > 0 %>
        <div class="col-md-3 selectOptions">
          <select id="friendsOption" class="btn btn-default dropdown-toggle">
    <% @friends.each do |friend| %>
      <option value="<%= friend.id %>"><%= friend.name %></option>
    <% end %>

  </select>
        </div>
        <div class="col-md-3">
            <button id="addFriend" class="btn btn-info">add</button>
        </div>
        <% end %>
        <% if @groups and @groups.length > 0 %>
        <div class="col-md-3 selectOptions" >
          <select id ="groupOption" class="btn btn-default dropdown-toggle">
    <% @groups.each do |group| %>
      <option value="<%= group.id %>"><%= group.name %></option> 
    <% end %>

  </select>
        </div>
        <div class="col-md-3">
            <button id="addGroup" class="btn btn-success">add</button>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

  

  




<script>
  var isDropDownEmpty = function (dropId) {
    return $("#"+dropId).html() && $("#"+dropId).html().indexOf("option") == -1
  }



  var GroupsAndFriendsRenderer = function(){


    this.onClicking = function(button){

    }
    var that = this;
    $( "#friends" ).on( "click", "button", function() {
      //alert("hi");
      that.onClicking(this);
      //$(this).parent().remove()

    });

    this.renderFriends = function(ids,names){
      var text = "<h2>added friends</h2>";
      for(var i = 0 ; i < ids.length ; i++){

        text += "<div class='col-md-4' name='friend"+ids[i]+"'><h4>"+names[ids[i]]+"</h4> <button class='btn btn-danger' name='"+ids[i]+"''>remove</button></div>"
      }
      $("#friends").html(text);   
    }
  }

  var AddedGroupsAndFriendsList = function(){
    this.originalFriendsIds = <%= @friends_id.to_s %>;
    for(var i = 0 ; i <this.originalFriendsIds.length ; i++){
      this.originalFriendsIds[i] += "";
    }
    //console.log( <%= @friends_id.to_s %> )
    this.friendIds =[];
    this.groupIds = [];

    this.friendsNames = {};
    this.groupNames = {};
    
    this.addFriend = function(name,id){
      if(this.friendIds.indexOf(id+"") == -1){
        this.friendIds.push(id+"")
        this.friendsNames[id] = name; 
        this.pushInFriend()
        //$("friend"+id).parent().remove()    
        $("#friendsOption option[value="+id+"]").remove()    
      }
        $("#firendsToBeAdded").val(this.friendIds+"")

        if(isDropDownEmpty("friendsOption")){
          $("#addFriend").prop("disabled", true)
        }

      //console.log(this.friendIds)
    }

    this.pushOutFriend = function (name,id) {
      
    }


    this.pushInFriend = function () {
      
    }

    this.removeFriend = function(id){

      var index = this.friendIds.indexOf(id+"");
      if(index != -1){
        this.friendIds.splice(index,1)
        this.pushOutFriend(this.friendsNames[id],id,"")   
        $("div[name='friend"+id+"']").remove()
      }
  //    console.log(this.friendIds)
      $("#firendsToBeAdded").val(this.friendIds+"")   

      $("#addFriend").prop("disabled", false)

    }


  }


  var DropDownRenderer = function(){

    


    this.getSelectedOption = function(){
      var id = $('#friendsOption :selected').val();
      var name = $('#friendsOption :selected').text();
      return ({"id":id, "name":name});

    }
    
    this.addOption = function(name,id){
      $('#friendsOption').append("<option value='"+id+"'>"+name+"</option>");
      
    }



  }


  var GroupList = function(friendsListKeeper){


    this.groupIds = [];
    this.groupNames = {};
    this.groupMembers = {};
    this.friendsListKeeper = friendsListKeeper;
    var that = this;
    
    this.onClicking = function(button) {

    }

    this.removeGroup = function(group){
      
      $('#groupOption').append("<option value='"+group+"'>"+this.groupNames[group+""]+"</option>");

      var myGroup = this.groupMembers[group];
      console.log(myGroup)
      for(var i = 0 ; i < myGroup.length ; i++){
        this.friendsListKeeper.removeFriend(myGroup[i].id+"");

      }

      $("#addGroup").prop("disabled", false)

    }
    
    this.addGroup = function(group , groupName , groupId){
      
      $("#groups").append("<div class='col-md-4' name='group"+groupId+"'><h4>"+groupName+"</h4> <button class='btn btn-danger' name='"+groupId+"'>remove</button></div>")

      for(var i = 0 ; i < group.length ; i++){
        that.friendsListKeeper.addFriend(group[i].name,group[i].id+"");
        

      }
      if(isDropDownEmpty("groupOption")){
        $("#addGroup").prop("disabled", true)
      }

    }
    $( "#groups" ).on( "click", "button", function() {
      //alert("hi");
      that.onClicking(this);
      $(this).parent().remove()

    });


    this.getGroupFriendsList = function( groupName , groupId){
      this.groupNames[groupId+""] = groupName;
      var ans = false;
      if(this.groupMembers[groupId] != undefined){
        this.addGroup(this.groupMembers[groupId] , groupName , groupId);
      }

      else{
        $.ajax({url:"/groups/"+groupId+"/show_users.json",success:function(result){
          var minAns = [];
          for (var i = 0 ; i < result.length ; i++){
            minAns.push({"name":result[i].name,"id":result[i].id})
          }
          
          //console.log(minAns)
          that.groupMembers[groupId] = minAns;
          that.addGroup(that.groupMembers[groupId] , groupName , groupId);
        }});
        
      }

    }
  }





  
   
var main = function(){
  
  var myGroupsAndFriendRenderer = new GroupsAndFriendsRenderer();
  var myGroupsAndFriends = new AddedGroupsAndFriendsList();
  var myDropDownRenderer = new DropDownRenderer();
  

  myGroupsAndFriends.pushOutFriend = function(name,id){
    
    console.log( $('#friendsOption').html().indexOf('value="'+id+'"') )
    console.log ( myGroupsAndFriends.originalFriendsIds.indexOf(id) )
    if($('#friendsOption').html().indexOf('value="'+id+'"') == -1 && myGroupsAndFriends.originalFriendsIds.indexOf(id) > -1 ){    
      myDropDownRenderer.addOption(name,id);
    }
  }
  myGroupsAndFriends.pushInFriend = function () {
    myGroupsAndFriendRenderer.renderFriends(myGroupsAndFriends.friendIds , myGroupsAndFriends.friendsNames);

  }



  
  myGroupsAndFriendRenderer.onClicking = function(clicker){
    var id = $(clicker).attr('name');
    myGroupsAndFriends.removeFriend(id);

  }
    
  $("#addFriend").click(function(){
    var id = $('#friendsOption :selected').val();
    var name = $('#friendsOption :selected').text();
    $('#friendsOption :selected').remove();
    myGroupsAndFriends.addFriend(name,id+"");

    //console.log(myGroupsAndFriends)


  })
  $("#addGroup").click(function(){
      var id = $('#groupOption :selected').val();
      var name = $('#groupOption :selected').text();
      $('#groupOption :selected').remove();
      myGroupList.getGroupFriendsList(name,id+"");;
    });

  var myGroupList = new GroupList(myGroupsAndFriends);
  myGroupList.onClicking = function (clicker) {
    var id = $(clicker).attr('name');
    myGroupList.removeGroup(id);

  }
  //myGroupList.getGroupFriendsList(1);
  //myGroupList.removeGroup(1);

}

main();
</script>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="page-header">
  <h1>Listing Orders</h1>
</div>
</div>

<div class="container">
  <table class="table">
    <thead>
      <tr>
      <th>Meal</th>
      <th>Restaurant</th>
      <th>Status</th>
      <th>Invited</th>
      <th>Joined</th>
      <th colspan="3"></th>
    </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
      <tr>
        <td><%= order.meal %></td>
        <td><%= order.restaurant %></td>
        <td><%= order.status %></td>
        <td><%= OrderUserJoin.where(order_id: order.id).count %></td>
        <td><%= OrderUserJoin.where(order_id: order.id).where(is_joined: 1).count %></td>
        <td><%= link_to 'Show',  order_path(order) %></td>
        <td><%= if order.status == "waiting"  
                  link_to 'Finish', order, method: :put  
                end 
            %></td>
        <td><%= if order.status == "waiting"  
                  link_to 'Cancel', order, method: :delete, data: { confirm: 'Are you sure?' } 
                  end %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <%= will_paginate @orders %>
</div>


<br>

<%= link_to 'New Order', new_order_path , class: 'btn btn-default'%>

app/views/orders/new.html.erb
<div class="container">
  <div class="page-header">
  <h1>New Order</h1>
</div>
</div>
<div class="container">
	<%= render 'form' %>
	<div class="container">
	<br/>
		<h4><%= link_to 'Back', orders_path %></h4>	
	</div>
</div>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="page-header">
  <h1>Order Details</h1>
      <%= if @isinvited && !@isJoined
        link_to 'Join',  joinuserinorder_path(@order.id, current_user.id), method: :put 
      end %>
</div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-body">
        <table class="table">
        <caption><h4>Items</h4></caption>
        <thead>
          <tr>
      <th>Person</th>
      <th>Item</th>
      <th>Amount</th>
      <th>Price</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
        </thead>
        <tbody>
          <%= render @order.items %>
        </tbody>
      </table>
      </div>
    </div>
    </div>
    <div class="col-md-4"><br/><br/><br/>
      <div class="container">
        <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#invited">Invited</button>
<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#joined">Joined</button>
      </div>
    </div>
  </div>
</div>
<br/>
<div class="container">
  <div class="row">
  <div class="panel panel-default">
    <div class="panel-body">
      <h4>Add Item</h4>
    <% if @isJoined || current_user.id == @order.user_id %>
<%= form_for(@item, url: order_items_path(@order.id)) do |f| %>
  <div class="field col-md-3">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control", placeholder: "Item name" %>
  </div>
  <div class="field col-md-1">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity, class: "form-control", placeholder: "Amount" %>
  </div>
  <div class="field col-md-2">
    <%= f.label :price %><br>
    <%= f.number_field :price, class: "form-control", placeholder: "Price" %>
  </div>
  <div class="field col-md-4">
    <%= f.label :comment %><br>
    <%= f.text_area :comment, class: "form-control", placeholder: "Comment" %>
  </div>
  <div class="actions col-md-2">
  <br/><br/>
    <%= f.submit "Add Item", class: "btn btn-default" %>
  </div>
<% end %>
<% end %>
    </div>
  </div>
  </div>
</div>
<p>
  <!--<strong>Meal:</strong>
  <%= @order.meal %>
</p>

<p>
  <strong>Restaurant:</strong>
  <%= @order.restaurant %>
</p>


<p>
  <strong>Status:</strong>
  <%= @order.status %>

</p>-->


<div class="container">
  <div class="row">
    <div class="col-md-6">
      
    </div>
    <div class="col-md-1">
      <%= link_to 'Back', orders_path %>
    </div>
    <div class="col-md-5">
      <%= image_tag @order.image.url(:medium) %>
    </div>
  </div>
</div>



<div id="invited" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Invited</h4>
      </div>
      <div class="modal-body">
        <table class="table">
          <thead>
              <tr>
                <th>User</th>
                  <th>email</th>
                  <th>Delete</th>
                  <th>Join</th>
              </tr>
          </thead>
          <tbody>
            <% @invitedFriends.each do |friend| %>
                  <tr>
                    <td><%= friend.name %></td>
                    <td><%= friend.email %></td>
                    <td><%= if current_user.id == @order.user_id
                              link_to 'remove',  removeUserfromorder_path(@order.id, friend.id), method: :delete, data: { confirm: 'Are you sure?' }
                            end %></td>
                    <td><%= if current_user.id == friend.id && !@isJoined
                              link_to 'Join',  joinuserinorder_path(@order.id, friend.id), method: :put 
                            end %></td>
                  </tr>
              <% end %>
          </tbody>
          
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

<div id="joined" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Joined</h4>
      </div>
      <div class="modal-body">
        <table class="table">
          <thead>
              <tr>
                <th>User</th>
                  <th>email</th>
                  <th>Delete</th>
              </tr>
          </thead>
          <tbody>
            <% @joinedFriends.each do |friend| %>
                  <tr>
                    <td><%= friend.name %></td>
                    <td><%= friend.email %></td>
                    <td><%=  if current_user.id == @order.user_id
                               link_to 'Destroy',  removeUserfromorder_path(@order.id, friend.id), method: :delete, data: { confirm: 'Are you sure?' } 
                               end %></td>
                  </tr>
              <% end %>
          </tbody>
          
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>