config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  resources :orders, except: :edit do
    member do
      post :new_member
    end
    resources :items, only: [:create, :destroy]
  end
  resources :groups do
    member do
      post :new_member
      delete :delete_member
    end
 end
 
  devise_for :users , :controllers => { :omniauth_callbacks => "callbacks" }

  sockets_for :notifications , only: [:show]
  
  sockets_for :users do
    sockets_for :notifications
  end

  get 'theorders/my_orders(.:format)', to: 'home#getorderbyuser'
  get 'theorders/friends_orders(.:format)', to: 'home#getorderbyfriends'
  get 'finduser/:id/finduser(.:format)', to: 'home#getuser'
  
  get 'allNotifications/:id', to: 'notifications#html_index'
  get 'notifications/:id/clear' , to: 'notifications#see_all_notification_of_me'
  get 'groups/:id/show_users(.:format)', to: "groups#show_users"
  

 resources :follows
match 'users/newfollow' => 'users#newfollow', :via => :post
 resources :users do
    member do
      get :follow
      get :unfollow
    end
 end

  root  'home#index' 

  
  delete '/orders/:order_id/:user_id', to: 'orders#removeUser', as: 'removeUserfromorder'
  put '/orders/:order_id/:user_id', to: 'orders#joinOrder', as: 'joinuserinorder'

end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :user
	belongs_to :order
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /items
  # GET /items.json
  def index
    @order = Order.find(params[:id])
    @items = @order.items
    #@items = Item.all.paginate(:page => params[:page], :per_page => 5)
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    if params[:item][:name] !="" && params[:item][:quantity] !="" && params[:item][:price] !=""
    @item = Item.new(item_params)
    @item.user_id=current_user.id
    @item.order_id=params[:order_id]
    respond_to do |format|
      @item.save
      format.html { redirect_to  order_path(params[:order_id]), notice: 'Item was successfully created.' }
    end
  else
      respond_to do |format|
        format.html { redirect_to order_path(params[:order_id]), notice: 'Item addition failed.' }
        format.json { head :no_content }
      end
  end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy

    @order = Order.find(params[:order_id])
    #@comment = @post.comments.find(params[:id])
    if @order.user_id.to_i == current_user.id.to_i  || @item.user_id.to_i == current_user.id.to_i
      @item.destroy
      respond_to do |format|
        format.html { redirect_to @order, notice: 'Item was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to post_path(@order)
      #render 'posts/show'
    end

    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :quantity, :price, :comment)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :order_id %><br>
    <%= f.number_field :order_id %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/_item.erb
		<tr>
	    	<th><%= User.find(item.user_id).email %></th>
	      	<th><%= item.name %></th>
	      	<th><%= item.quantity %></th>
	      	<th><%= item.price %></th>
	      	<th><%= item.comment %></th>
	      	<th><%= if item.user_id.to_i == current_user.id.to_i
	      	 link_to 'Destroy item', [item.order, item],
               method: :delete,
               data: { confirm: 'Are you sure?' }
               end %></th>
	    </tr>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th>Order</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.user_id %></td>
        <td><%= item.order_id %></td>
        <td><%= item.quantity %></td>
        <td><%= item.price %></td>
        <td><%= item.comment %></td>
        <td><%= link_to 'Show', order_items_path %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @items %>
<br>

<%= link_to 'New Item', new_order_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @item.user_id %>
</p>

<p>
  <strong>Order:</strong>
  <%= @item.order_id %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @item.quantity %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @item.comment %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>