config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  resources :orders, except: :edit do
    member do
      post :new_member
    end
    resources :items, only: [:create, :destroy]
  end
  resources :groups do
    member do
      post :new_member
      delete :delete_member
    end
 end
 
  devise_for :users , :controllers => { :omniauth_callbacks => "callbacks" }

  sockets_for :notifications , only: [:show]
  
  sockets_for :users do
    sockets_for :notifications
  end

  get 'theorders/my_orders(.:format)', to: 'home#getorderbyuser'
  get 'theorders/friends_orders(.:format)', to: 'home#getorderbyfriends'
  get 'finduser/:id/finduser(.:format)', to: 'home#getuser'
  
  get 'allNotifications/:id', to: 'notifications#html_index'
  get 'notifications/:id/clear' , to: 'notifications#see_all_notification_of_me'
  get 'groups/:id/show_users(.:format)', to: "groups#show_users"
  

 resources :follows
match 'users/newfollow' => 'users#newfollow', :via => :post
 resources :users do
    member do
      get :follow
      get :unfollow
    end
 end

  root  'home#index' 

  
  delete '/orders/:order_id/:user_id', to: 'orders#removeUser', as: 'removeUserfromorder'
  put '/orders/:order_id/:user_id', to: 'orders#joinOrder', as: 'joinuserinorder'

end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to 'YalNotlob',  user_session , class: 'navbar-brand' %>
    </div>
<% if user_signed_in? %>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home',   home_index_path  %><span class="sr-only">(current)</span></li>
        <li><%= link_to 'Freinds',  users_path %></li>
        <li><%= link_to 'Group',  groups_path %></li>
        <li><%= link_to 'Order',  orders_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li id="UnSeenNotifications" style="color:red;"></li>
        <li id="notifications" class="dropdown"></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %><span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'Profile', edit_user_registration_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
            <li role="separator" class="divider"></li>
          </ul>
            <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
          <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Log In', new_user_session_path %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
      </ul>
    </div>
    <% end %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
    <%= javascript_include_tag "entangled-js.js" %>
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_user_widget.html.erb
<% if user_signed_in? %>
  <p>Welcome <%= current_user.email %></p>
  <%= link_to 'Logged In [click to logout]', destroy_user_session_path, :method => :delete %>
<% else %>
  <p>You are not signed in.</p>
  <%= link_to 'Login', new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render '/layouts/nav' %>
    <% if user_signed_in? %>
      <script type="text/javascript">

        var firstTime = true        

        var myId = "<%= current_user.id %>"

        var notificationTalking = new Entangled('ws://localhost:3000/users/'+myId+'/notifications');
        

        var readNotification = function(notificationId ,orderId){
           notificationTalking.find( notificationId , function(err, notification) {
              
              //console.log(notification)

              notification.$update({ isRead: true }, function(err, notification) {
                // Do stuff after update
              
            });


           });
            window.location.replace("/orders/"+orderId)
          
        }



        var NotificationsWrapper = function(){
          var that = this;

          this.isNotificationsClicked = function(){
            return $("#notifications").hasClass("open")
                                 
          }

          this.seeAllNotifications = function(){
            $.ajax({url: '<%= "/notifications/#{current_user.id}/clear" %>'});
          }
          this.setNotificationScene = function (num) {
            if(num == 0){
              num="";
            }
            $("#UnSeenNotifications").html(num+"")
          }
          
          this.checkNotifictionClicks = function(){
            if(this.isNotificationsClicked()){
              this.seeAllNotifications();
              this.setNotificationScene(0);              
            }

            setTimeout(function(){that.checkNotifictionClicks()},100)
          }

        }
        var noteWrapper = new NotificationsWrapper();
        noteWrapper.checkNotifictionClicks();

  


        notificationTalking.all( function(err, notifications) {
          // All messages available here
          var holder=document.getElementById("notifications");
          //var newHolder = '<button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Dropdown Example<span class="caret"></span></button><ul class="dropdown-menu">'
          var newHolder = '<a id="noteClicker" class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="false"> <%= fa_icon "bell-o" , :class => "fa-2x"%><span class="caret"></span></a><ul class="dropdown-menu">'

          var numberOfUnSeen = 0;
          var limitOfNotification = notifications.length-11;
          limitOfNotification = Math.max(0,limitOfNotification);
          var classes = "notif";

          for( var i = notifications.length-1 ; i >= limitOfNotification  ; i-- ){
            if(notifications[i].isRead){
              classes = "notif dark";              
            }
            else{
              classes = "notif"; 
            }

            if(!notifications[i].isRead|| true){
              newHolder += "<li class='"+classes+"' onclick="+"readNotification('"+notifications[i].id +"','"+notifications[i].orderId+"') >" + notifications[i].message+"</li>";
            if(!notifications[i].isSeen){
                numberOfUnSeen += 1;              
            }

              //console.log(notifications[i]);


            }
          }
          if($("#notifications").hasClass("open")){
               numberOfUnSeen = 0;              

          }
          if(numberOfUnSeen > 0 && !firstTime  ){
            new Audio('/Bell-ding.mp3').play();

          }
          if(firstTime){
            firstTime = false;
          }
          noteWrapper.setNotificationScene(numberOfUnSeen)
          //$("#UnSeenNotifications").html(numberOfUnSeen)


          newHolder += '<%= link_to "show all notifications" , "/allNotifications/#{current_user.id}" %>'
          newHolder += "</ul>";
          holder.innerHTML = newHolder;       

        
          

        });


        // Set up association  
        //usersTalking.hasMany('notificaions');
      
      </script>
    
    <% end %>



<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>
</div>

<div class="container"><%= yield :top_content %>
</div>

<div class="container">
    <h1><%= yield :header %></h1>
  <%= yield %>
</div>

<div class="push"></div>

</div>

</body>
</html>